when:
  instance: ci.kokuwa.io
  repo: woodpecker/kyverno
  event: [manual, push]
  branch: main
  path: [.woodpecker/dockerhub.yaml, README.md]

steps:

  metadata:
    image: kokuwaio/dockerhub-metadata
    settings:
      repository: kokuwaio/kyverno
      description-short: A WoodpeckerCI plugin to run kyverno and kubectl to lint kubernetes manifests.
      categories: [developer-tools, integration-and-delivery]
      username: {from_secret: dockerhub_username}
      password: {from_secret: dockerhub_password}
